### ISSUE TITLE
10 staffs

### ISSUE THREAD

**Issue by ivanivanet89** [Desoroxxx/Mystic-Staffs#2]
how to remove binding with mowsie mobs mod? I don't want to play with this mod, but I want to have all 10 staves.

**Comment by Desoroxxx** [comment]
> how to remove binding with mowsie mobs mod? I don't want to play with this mod, but I want to have all 10 staves.

This is not possible some staff are direct integrations with Mowzie's Mobs and thus require the mod.

**Comment by ivanivanet89** [comment]
> > как убрать привязку с модом mowsie mobs? Я не хочу играть с этим модом, но я хочу иметь все 10 посохов.
> 
> Это невозможно, некоторые сотрудники имеют прямую интеграцию с Mowzie's Mobs и поэтому требуют мод.

я исправил эту проблему , я отключил спавн мобов в config. Ваш мод чудесный, он самый ванильный из всех других модов на магию.
