### ISSUE TITLE
Solar Beam soft crash

### ISSUE THREAD

**Issue by Sereath** [Desoroxxx/Mystic-Staffs#3]
Noticed that I get these when using the Solar Beam staff, yes also using Mowzie's Mobs.
But I can still play. So just a heads up.

https://gist.github.com/Sereath/00e46eaeccc2404bd7482bcd13051c1f

**Comment by Desoroxxx** [comment]
I will look into it, the way I do things right now is pretty cursed iirc

**Comment by Desoroxxx** [comment]
Actually I am doing it the intended way, the issue does not come from me, it comes from Mowzie's Mobs networking code which is not done properly, sadly there is nothing I can do about this.

**Comment by Sereath** [comment]
For what it's worth, it only happens when you are **not** under the effects of:
![image](https://github.com/Desoroxxx/Mystic-Staffs/assets/54506307/97577f95-9834-45b9-ae3b-efc24a064acc)
